-- Secrets live in Supabase Vault and never leave the database / functions.
-- Edge Functions (service role only) read them; VAPID keys are generated by the
-- functions on first use; the cron secret is generated right here.

create or replace function public.nora_get_secret(p_name text)
returns text language sql stable security definer set search_path = '' as $$
  select decrypted_secret from vault.decrypted_secrets where name = p_name limit 1
$$;

create or replace function public.nora_ensure_secret(p_name text, p_value text)
returns text language plpgsql security definer set search_path = '' as $$
declare v text;
begin
  perform pg_advisory_xact_lock(hashtext(p_name));
  select decrypted_secret into v from vault.decrypted_secrets where name = p_name limit 1;
  if v is null then
    perform vault.create_secret(p_value, p_name);
    v := p_value;
  end if;
  return v;
end $$;

revoke all on function public.nora_get_secret(text) from public, anon, authenticated;
revoke all on function public.nora_ensure_secret(text, text) from public, anon, authenticated;
grant execute on function public.nora_get_secret(text) to service_role;
grant execute on function public.nora_ensure_secret(text, text) to service_role;

-- shared secret between pg_cron and the dispatch function (random, generated in the DB)
select public.nora_ensure_secret('nora_cron_secret', replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''));
